services:
  postgres:
    image: postgres:16-alpine
    container_name: jwt_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: localdbuser
      POSTGRES_PASSWORD: localPass123
      POSTGRES_DB: jwt_auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U localdbuser -d jwt_auth_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
