version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localdbuser
      POSTGRES_PASSWORD: localPass123
      POSTGRES_DB: local_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
